// Reading plans — a port of `Plans` (Bible.kt) and `ChronoOrder.kt`, so a day
// holds the same chapters on the web as on Android.
//
// Days are pinned to the canonical KJV chapter grid: day contents, and the day
// numbers progress is kept under, are identical whatever is being read. The
// sheet pivots each chapter into the primary translation through the versemap
// at display time (LXX psalter -1 etc.), exactly as PlansScreen.kt does.
//
// Pure apart from loadPlanState/savePlanState: `plans.test.ts` runs the rest
// under node, and checks CHRONO_ORDER against ChronoOrder.kt byte for byte.

/** Chapters per canon book in KJV versification (Gen 50 ... Rev 22), 1189 in all. */
export const KJV_CHAPTERS = [
  50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10,
  42, 150, 31, 12, 8, 66, 52, 5, 48, 12, 14, 3, 9, 1, 4, 7, 3, 3, 3,
  2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4,
  3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22,
];

/** ChronoOrder.kt ORDER, verbatim: "book:chapter" or "book:first-last", book
 *  0-based, chapters 1-based KJV. Generated by tools/build_chrono_plan.py. */
export const CHRONO_ORDER =
  "0:1-11 17:1-42 0:12-50 1:1-40 2:1-27 3:1-36 4:1-32 18:90-91 4:33-34 " +
  "5:1-24 6:1-21 7:1-4 8:1-18 18:59 8:19-21 18:56 18:34 8:22 18:142 " +
  "18:52 8:23 18:54 18:63 8:24 18:57 8:25-26 18:7 18:5 18:11-14 18:17 " +
  "18:22 18:25-28 18:31 18:35 18:64 18:69 18:86 18:109 18:140-141 " +
  "18:143 8:27-31 12:10 9:1-5 12:11-12 18:2 18:101 18:110 9:6 12:13-16 " +
  "18:96 18:105-106 18:8 18:15 18:19 18:24 18:29 18:33 18:65-68 18:93 " +
  "18:95 18:97-100 18:104 9:7 12:17 18:16 18:23 18:36 18:39 18:62 " +
  "18:84 9:8-9 12:18 18:60 18:108 9:10 12:19 18:9-10 18:20-21 18:44 " +
  "9:11-12 12:20 18:51 18:32 18:38 18:6 9:13-15 18:3-4 18:55 9:16-18 " +
  "18:41 18:61 18:70 9:19-21 18:40 18:58 9:22 18:18 9:23-24 12:21 " +
  "18:30 12:22-25 18:1 18:42-43 18:45 18:49-50 18:53 18:73 18:77-78 " +
  "18:81-82 18:88 18:92 18:94 18:103 18:111-118 18:122 18:124 18:131 " +
  "18:133 18:138-139 18:144-145 12:26-29 10:1-2 18:37 18:71 10:3 13:1 " +
  "18:72 10:4 21:1-8 10:5-6 13:2-3 10:7 13:4 10:8 13:5 18:132 13:6-7 " +
  "18:135-136 10:9 13:8 18:127 19:1-31 10:10 13:9 20:1-12 10:11-14 " +
  "13:10-12 18:89 10:15 13:13-16 10:16 13:17 10:17-22 13:18-20 " +
  "18:46-48 18:83 11:1-8 13:21 11:9-10 13:22 11:11-12 13:23-24 28:1-3 " +
  "11:13-14 13:25 31:1-4 29:1-9 11:15 13:26 22:1-6 13:27 32:1-7 11:16 " +
  "13:28 22:7-12 27:1-14 11:17 18:80 13:29-31 22:13-35 11:18-19 13:32 " +
  "22:36-37 18:75-76 11:20 22:38-66 11:21 13:33 33:1-3 11:22 13:34 " +
  "35:1-3 23:1-6 11:23 13:35 34:1-3 23:26 23:7-20 23:22-23 23:25 " +
  "23:46-47 26:1 23:36 23:45 26:2 23:35 23:48-49 26:3 11:24 23:24 " +
  "23:29 23:27-28 23:50-51 25:1-24 23:21 23:34 23:30-33 23:37-38 " +
  "11:25 13:36 23:39 23:52 24:1-5 30:1 18:74 18:79 18:137 23:40-44 " +
  "25:25-48 26:4 26:7-8 26:5 26:9 18:102 26:6 12:1-9 14:1-3 18:107 " +
  "18:85 18:87 18:126 26:10-12 14:4 36:1-2 37:1-8 14:5-6 37:9-14 " +
  "16:1-10 14:7-10 18:119 15:1-7 18:120-121 18:123 18:125 18:128-130 " +
  "18:134 15:8-13 18:146-150 38:1-4 41:1 39:1 41:2 39:2-3 40:1 41:3 " +
  "42:1 39:4 41:4-5 42:2-5 40:2 39:12 40:3 41:6 39:5-8 41:7 39:11 " +
  "41:8 40:4-5 39:13 39:9-10 39:14 40:6 41:9 42:6 39:15 40:7 39:16 " +
  "40:8 39:17 40:9 39:18 42:7-10 41:10-17 42:11 41:18 39:19 40:10 " +
  "39:20 41:19 42:12 39:21 40:11 39:22 40:12 41:20 39:23-24 40:13 " +
  "41:21 39:25-26 40:14 41:22 42:13-17 39:27 40:15 41:23 42:18-19 " +
  "39:28 40:16 41:24 42:20-21 43:1-12 58:1-5 43:13-15 47:1-6 43:16-18 " +
  "51:1-5 52:1-3 43:19 45:1-16 46:1-13 44:1-16 43:20-28 48:1-6 50:1-4 " +
  "56:1 49:1-4 53:1-6 55:1-3 59:1-5 57:1-13 54:1-4 60:1-3 64:1 61:1-5 " +
  "62:1 63:1 65:1-22";

/** A chapter on the KJV grid: [book, chapter], both 0-based. */
export type Chap = [number, number];

export interface PlanDay {
  /** 1-based, as progress stores it. */
  day: number;
  chapters: Chap[];
}

export interface Plan {
  id: string;
  /** i18n keys, the Android string names. */
  title: string;
  desc: string;
  days: PlanDay[];
  /** Day -> era heading key, on the day holding the era's first chapter. */
  eraByDay: Map<number, string>;
}

/** Historical eras, as ChronoOrder.kt: [book, 0-based KJV chapter, key]. */
const ERAS: [number, number, string][] = [
  [0, 0, "era_beginning"],
  [17, 0, "era_patriarchs"],
  [1, 0, "era_exodus"],
  [3, 0, "era_wilderness"],
  [5, 0, "era_conquest"],
  [6, 0, "era_judges"],
  [8, 0, "era_saul"],
  [12, 9, "era_david"],
  [10, 0, "era_solomon"],
  [10, 11, "era_divided"],
  [11, 14, "era_isaiah"],
  [11, 20, "era_last_kings"],
  [23, 25, "era_fall"],
  [23, 39, "era_exile"],
  [12, 0, "era_return"],
  [41, 0, "era_christ"],
  [43, 0, "era_church"],
  [65, 0, "era_revelation"],
];

/** Plans.distribute: a flat chapter list spread evenly, ceil per day. */
export function distribute(chapters: Chap[], totalDays: number): PlanDay[] {
  const days = Math.max(1, Math.min(totalDays, chapters.length));
  const out: PlanDay[] = [];
  let index = 0;
  for (let day = 0; day < days; day += 1) {
    const take = Math.ceil((chapters.length - index) / (days - day));
    out.push({ day: day + 1, chapters: chapters.slice(index, index + take) });
    index += take;
  }
  return out;
}

/** ChronoOrder.chapters(): every canon chapter once. Throws on a repeat or a
 *  count other than 1189 — a broken order must not quietly become a plan. */
export function chronoChapters(order: string = CHRONO_ORDER): Chap[] {
  const out: Chap[] = [];
  const seen = new Set<string>();
  for (const token of order.split(" ")) {
    const [book, range] = token.split(":");
    const b = Number(book);
    const [first, last = first] = range.split("-").map(Number);
    for (let ch = first; ch <= last; ch += 1) {
      const k = String(b) + ":" + String(ch - 1);
      if (seen.has(k)) throw new Error("CHRONO_ORDER repeats chapter " + k);
      seen.add(k);
      out.push([b, ch - 1]);
    }
  }
  if (out.length !== 1189) throw new Error("CHRONO_ORDER expands to " + String(out.length) + " chapters, expected 1189");
  return out;
}

export function eraByDay(days: PlanDay[]): Map<number, string> {
  const m = new Map<number, string>();
  for (const [b, c, key] of ERAS) {
    const d = days.find((x) => x.chapters.some((y) => y[0] === b && y[1] === c));
    if (d !== undefined && !m.has(d.day)) m.set(d.day, key);
  }
  return m;
}

let cached: Plan[] | null = null;

/** The six plans, in the Android tab order. */
export function buildPlans(): Plan[] {
  if (cached !== null) return cached;
  const all: Chap[] = [];
  KJV_CHAPTERS.forEach((n, b) => {
    for (let c = 0; c < n; c += 1) all.push([b, c]);
  });
  const chrono = distribute(chronoChapters(), 365);
  const plan = (id: string, title: string, desc: string, days: PlanDay[], eras = new Map<number, string>()): Plan => ({ id, title, desc, days, eraByDay: eras });
  cached = [
    plan("year", "plan_year", "plan_year_desc", distribute(all, 365)),
    plan("chrono", "plan_chrono", "plan_chrono_desc", chrono, eraByDay(chrono)),
    plan("nt90", "plan_nt90", "plan_nt90_desc", distribute(all.filter((x) => x[0] >= 39), 90)),
    plan("gospels30", "plan_gospels", "plan_gospels_desc", distribute(all.filter((x) => x[0] >= 39 && x[0] <= 42), 30)),
    plan("prov31", "plan_proverbs", "plan_proverbs_desc", distribute(all.filter((x) => x[0] === 19), 31)),
    plan("ps75", "plan_psalms", "plan_psalms_desc", distribute(all.filter((x) => x[0] === 18), 75)),
  ];
  return cached;
}

/** The first day not done, or the last day when every day is (PlansScreen). */
export function nextDay(plan: Plan, done: Set<number>): number {
  return plan.days.find((d) => !done.has(d.day))?.day ?? plan.days.length;
}

// ---- Progress, kept in this browser only (web/README.md house rule 4) ----

export interface PlanState {
  /** The plan last open, as Store.lastPlanId. */
  last: string;
  /** Plan id -> the day numbers ticked. */
  done: Record<string, number[]>;
  /** The daily reading streak, as Store.bumpStreak: days in a row the app was
   *  opened, and the local day (YYYY-MM-DD) it last counted. */
  streak: number;
  streakDay: string;
}

export const EMPTY_PLANS: PlanState = { last: "", done: {}, streak: 0, streakDay: "" };

/** Stored JSON -> PlanState; anything malformed is dropped, never thrown. */
export function cleanPlanState(x: unknown): PlanState {
  if (x === null || typeof x !== "object") return { ...EMPTY_PLANS, done: {} };
  const p = x as Record<string, unknown>;
  const done: Record<string, number[]> = {};
  if (p.done !== null && typeof p.done === "object") {
    for (const [id, days] of Object.entries(p.done as Record<string, unknown>)) {
      if (!Array.isArray(days)) continue;
      const ok = [...new Set(days.filter((d): d is number => Number.isInteger(d) && d >= 1 && d <= 365))].sort((a, b) => a - b);
      if (ok.length > 0) done[id] = ok;
    }
  }
  return {
    last: typeof p.last === "string" ? p.last : "",
    done,
    streak: Number.isInteger(p.streak) && (p.streak as number) >= 0 ? (p.streak as number) : 0,
    streakDay: typeof p.streakDay === "string" && /^\d{4}-\d{2}-\d{2}$/.test(p.streakDay) ? p.streakDay : "",
  };
}

export function toggled(s: PlanState, id: string, day: number): PlanState {
  const cur = new Set(s.done[id] ?? []);
  if (cur.has(day)) cur.delete(day);
  else cur.add(day);
  const done = { ...s.done };
  if (cur.size === 0) delete done[id];
  else done[id] = [...cur].sort((a, b) => a - b);
  return { ...s, done };
}

export function reset(s: PlanState, id: string): PlanState {
  const done = { ...s.done };
  delete done[id];
  return { ...s, done };
}

/** A local calendar day as YYYY-MM-DD. */
export function dayOf(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return String(d.getFullYear()) + "-" + p(d.getMonth() + 1) + "-" + p(d.getDate());
}

/** Store.touchStreak: same day keeps it (at least 1), the next day adds one,
 *  a gap restarts at 1. Called once per app open. */
export function bumped(s: PlanState, now: Date): PlanState {
  const today = dayOf(now);
  if (s.streakDay === today) return s.streak >= 1 ? s : { ...s, streak: 1 };
  const y = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
  return { ...s, streak: s.streakDay === dayOf(y) ? s.streak + 1 : 1, streakDay: today };
}

const KEY = "hexapla.plans.v1";

export function loadPlanState(): PlanState {
  try {
    const raw = window.localStorage.getItem(KEY);
    return raw === null ? { ...EMPTY_PLANS, done: {} } : cleanPlanState(JSON.parse(raw));
  } catch {
    return { ...EMPTY_PLANS, done: {} };
  }
}

export function savePlanState(s: PlanState): void {
  try {
    window.localStorage.setItem(KEY, JSON.stringify(s));
  } catch {
    // Storage unavailable: ticks last until the page closes.
  }
}
