package com.aleks.hexapla

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/**
 * Which musical bed belongs under which passage.
 *
 * Data comes from `assets/mood_map.json`, generated by tools/build_mood_map.py,
 * which asserts that all 1,189 canonical chapters resolve to exactly one mood.
 *
 * ⚠⚠ THE MAP IS KEYED TO CANONICAL KJV COORDINATES, and [moodFor] pivots the
 * displayed translation's own numbering through [VerseMap] before looking
 * anything up. Translations here keep their AUTHENTIC native numbering — the
 * Synodal and Elizabeth psalters are LXX-numbered, Luther and WLC use Masoretic
 * bounds, Karoli keeps Calvin numbering — so a lookup done on the displayed
 * numbers would hand Psalm 23 the wrong mood in Russian and be quietly wrong
 * across whole books in Hungarian and Czech.
 * This is the same defect class already fixed three times in this app: plan
 * days pinned to the canonical grid (2464f04), bookmarks pivoted at display
 * time (845f588), and notes/highlights rekeyed in 1.4.2. `chapterIndexFor` was
 * deleted precisely because it fixed the chapter but never the verse.
 *
 * Resolution order, later winning: book default -> chapter range -> anchor
 * (which may turn mid-chapter at a verse) -> track pin.
 */
object MoodMap {

    /** A resolved bed: a mood, and optionally one specific track pinned to it. */
    data class Bed(val mood: String, val track: String? = null)

    const val SILENCE = "silence"

    private var bookDefault: List<String> = emptyList()
    private var ranges: List<Range> = emptyList()
    private var anchors: Map<Long, Anchor> = emptyMap()
    private var pins: Map<Long, String> = emptyMap()
    private var loaded = false

    private data class Range(val book: Int, val from: Int, val to: Int, val mood: String)
    private data class Anchor(val mood: String, val turns: List<Pair<Int, String>>)

    /** Anchors and pins are keyed by book/chapter, packed so lookup is a hash hit. */
    private fun key(book: Int, chapter: Int): Long = book.toLong() * 1000L + chapter

    suspend fun load(context: Context) {
        if (loaded) return
        withContext(Dispatchers.IO) {
            try {
                val root = JSONObject(
                    context.assets.open("mood_map.json").bufferedReader().use { it.readText() }
                )
                bookDefault = root.getJSONArray("bookDefault").let { a ->
                    List(a.length()) { a.getString(it) }
                }
                ranges = root.getJSONArray("ranges").let { a ->
                    List(a.length()) {
                        val o = a.getJSONObject(it)
                        Range(o.getInt("book"), o.getInt("from"), o.getInt("to"), o.getString("mood"))
                    }
                }
                anchors = root.getJSONArray("anchors").let { a ->
                    buildMap {
                        for (i in 0 until a.length()) {
                            val o = a.getJSONObject(i)
                            val turns = o.optJSONArray("turns")?.let { t ->
                                List(t.length()) { j ->
                                    val to = t.getJSONObject(j)
                                    to.getInt("verse") to to.getString("mood")
                                }
                            } ?: emptyList()
                            put(key(o.getInt("book"), o.getInt("chapter")),
                                Anchor(o.getString("mood"), turns))
                        }
                    }
                }
                pins = root.optJSONArray("trackPin")?.let { a ->
                    buildMap {
                        for (i in 0 until a.length()) {
                            val o = a.getJSONObject(i)
                            put(key(o.getInt("book"), o.getInt("chapter")), o.getString("track"))
                        }
                    }
                } ?: emptyMap()
                loaded = true
            } catch (_: Exception) {
                // A missing or malformed map must never break playback: callers
                // fall back to the uniform bed, which is the pre-1.6.3 behaviour.
                loaded = false
            }
        }
    }

    val isLoaded: Boolean get() = loaded

    /**
     * The bed for a passage in [translationId]'s own numbering.
     *
     * [verse] may be -1 when nothing is playing yet; anchors then resolve to
     * their opening mood, which is what a chapter starts on anyway.
     */
    fun moodFor(translationId: String, book: Int, chapter: Int, verse: Int): Bed {
        if (!loaded || book < 0 || chapter < 0) return Bed("narrative")

        // ── the pivot. Everything below is canonical. ────────────────────
        // ⚠⚠ VerseMap IS 1-BASED ON BOTH SIDES; THIS MAP IS 0-BASED.
        // build_mood_map.py emits 0-based book/chapter/verse (see its header),
        // and every other VerseMap caller in the app converts on the way in —
        // ReaderScreen does `chapter + 1, verse + 1` in seven places. This one
        // did not, and passed raw 0-based coordinates into a 1-based API.
        // TWO defects came out of that, found 2026-08-23 when the owner heard
        // CHEERFUL music under the Synodal Psalm 87 (= KJV 88, the darkest
        // psalm in the psalter):
        //   1. At CHAPTER START the pivot silently did nothing. Playback.verse
        //      is -1 between chapters, so verse 0 went in, and 0 never falls
        //      inside a 1-based run — toKjv fell through to identity and the
        //      LXX psalter was never pivoted at all. Chapter start is exactly
        //      when the bed is chosen, so this is the case that is heard.
        //   2. The 1-based chapter it returned was then looked up in the
        //      0-based map. Mid-chapter the two errors happened to cancel for
        //      equal-length runs, which is why this looked fine when spot-
        //      checked on a verse.
        // Measured across every mapped translation: 644 of 7311 chapters
        // resolved to the wrong mood at chapter start (syn 101, csl 101,
        // wyc 106, zoh 103, vul 100, bak 100, and a tail of others).
        // ▶ Convert in, convert back out. Unmapped translations still resolve
        //   to identity, so kjv/ylt and friends are unaffected.
        val (kc1, kv1) = try {
            VerseMap.toKjv(
                translationId, book, chapter + 1,
                if (verse >= 0) verse + 1 else 1
            )
        } catch (_: Exception) {
            (chapter + 1) to (if (verse >= 0) verse + 1 else 1)
        }
        val kc = kc1 - 1
        val kv = kv1 - 1

        // Apocrypha (book >= 66) resolve by book default plus ranges only; the
        // generator refuses anchors there because verse numbering inside the
        // apocrypha is not mapped by VerseMap.
        var mood = bookDefault.getOrNull(book) ?: "narrative"
        for (r in ranges) {
            if (r.book == book && kc >= r.from && kc <= r.to) mood = r.mood
        }
        anchors[key(book, kc)]?.let { a ->
            mood = a.mood
            // Turns are ordered; the last one at or before this verse wins.
            for ((v, m) in a.turns) if (kv >= v) mood = m
        }
        return Bed(mood, pins[key(book, kc)])
    }
}
